prismaneui/prismane

- .storybook/main.ts
Removed postcss from storybook config. This is not needed since vite comes with PostCSS support. Thats only needed for Webpack.
> Updates storybook config

- src/components/Backdrop/Backdrop.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Drawer/Drawer.tsx
- src/components/Modal/Modal.tsx
This merge fixes the issue that enabled users to scroll when an overlay component was shown (Drawer, Modal, Dialog).
> Disable scrolling when overlay components are open

- src/components/Box/Box.tsx
- src/themes/base.ts
- src/themes/theme.ts
- src/types.ts
This merge adds the border-radius prebuilt values to the theme object, which provides even more customization.
> Add Border Radius To Theme Object

- src/components/SelectField/SelectField.tsx
This merge fixes a bug where the Menu component is still shown even though there are no values to display.
> Hide Menu When No Options Are Available

- src/components/TextField/TextField.tsx
- src/hooks/useFocusTrap/useFocusTrap.stories.tsx
- src/hooks/useFocusTrap/useFocusTrap.test.tsx
- src/hooks/useFocusTrap/useFocusTrap.ts
This merge fixes the useFocusTrap hook. The hook now can deeply focus inputs that use the `data-initialfocus` attribute and to be correctly toggled by the `isOpen` boolean.
> Fix useFocusTrap Hook

- .storybook/preview.tsx
- src/components/Toaster/Toast/Toast.tsx
- src/components/Toaster/Toaster.stories.tsx
This merge fixes an issue with the Toast component that didn't remove the toasts from the DOM after animating out.
> Fix toasts not removed after hiding

- src/components/Dialog/Dialog.tsx
This merge fixes an issue where the dialog closes when clicked inside instead of stopping the propagation of the event.
> Fix Dialog Closing When Clicked Inside

- src/components/Container/Container.tsx
This merge fixes a bug where the maxSize prop type of the Container component didn't have the full list of supported values and resulted in a type error when passing a valid value.
> Fix Container maxSize Prop Type To Support Sizes Up To 6xl

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
This merge fixes an issue where the border radius of the Button component didn't scale consistently on bigger sizes.
> Change Button's Border Radius On Larger Sizes

- .storybook/preview-head.html
- .storybook/preview.tsx
- package.json
- src/components/PrismaneProvider/PrismaneProvider.tsx
- src/index.css
- src/themes/base.ts
- src/themes/theme.ts
- src/types.ts
This merge adds the font-family CSS rule to the theme object and includes a preinstalled Poppins font with Prismane.
> Add fontFamily to theme object + Ship with Poppins font preinstalled

- src/components/Grid/Grid.stories.tsx
- src/components/Grid/Grid.tsx
- src/components/Grid/GridItem/GridItem.tsx
This merge introduces an `area` prop to the `Grid.Item` component and a `templateAreas` prop to the `Grid` component.
> Add Area Props To Grid Components

- src/components/Form/Form.tsx
This merge removes the unneeded type declarations of the `onReset` and `onSubmit` props.
> Remove onSubmit and onReset Prop Types From Form Component

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
This merge introduces the new `icon` prop on the `Checkbox` component, which allows change of the default icon of the checkbox field.
> Add Checkbox Icon Prop

- src/components/Alert/Alert.tsx
This merge fixes an issue with the `Alert` component, where the custom action component passed to the `action` prop did not close the alert.
> Fix Custom Alert Action To Close Alert Too

- src/components/Button/Button.tsx
This merge changes the `Button` component's loading state spinner to show instead of the icon.
> Button Loading Spinner To Be Shown As An Icon

- package.json
- src/types.ts
- yarn.lock
This merge adds CSS type support to all of Prismane's shorthand styling props.
> Add CSS types to props

- src/components/Grid/Grid.tsx
This merge fixes the prop types of the `templateColumns` and `templateRows` props of the `Grid` component.
> fix: fix grid template prop types

- src/components/Accordion/AccordionIcon/AccordionIcon.tsx
This merge fixes the prop type of the `children` prop of the `Accordion.Item` component.
> fix: fix accordion item children prop type

- src/components/AutocompleteField/AutocompleteField.tsx
This merge fixes the prop type of the `filter` prop of the `AutocompleteField` component.
> fix: fix autocomplete field filter prop type

- src/components/Button/Button.tsx
This merge fixes the `Button` component's border color when it has a `tertiary` variant and has a `fillOnHover` prop.
> fix: fix button's border color with tertiary variant and fill on hover

- src/components/Field/Field.tsx
- src/components/NativeDateField/NativeDateField.tsx
- src/components/NativeSelectField/NativeSelectField.tsx
- src/components/NumberField/NumberField.tsx
- src/components/PasswordField/PasswordField.tsx
- src/components/PinField/PinField.tsx
- src/components/SegmentedField/SegmentedField.tsx
- src/components/SelectField/SelectField.tsx
- src/components/TextField/TextField.tsx
- src/components/TextareaField/TextareaField.tsx
- src/types.ts
This merge fixes the functionality of the `disabled` and `readOnly` props across multiple field components: `NativeSelectField`, `NumberField`, `PinField`, `SelectField`, `SegmentedField`, `NativeDateField`, `PasswordField`, `TextField`, `TextareaField`.
> Fix disabled and read only fields

- src/components/Field/Field.tsx
- src/components/PinField/PinField.tsx
- src/types.ts
This merge fixes the props that are passed to each digit field inside the `PinField` component.
> fix: fix PinField's passed props

- src/components/SelectField/SelectField.tsx
This merge fixes an issue in the `SelectField` component, where its dropdown wrapper changed its height and made the field higher than other fields.
> fix: fix SelectField's dropdown making it higher than other fields

- src/components/TextareaField/TextareaField.stories.tsx
- src/components/TextareaField/TextareaField.tsx
This merge adds the `resize` prop to the `TextareaField` allowing it to be resized.
> feat: add resize prop to TextareaField

- src/components/Box/Box.tsx
This merge makes the `fs` prop support not only Prismane's breakpoints but any other valid string or number value.
> feat: add dual value support to fs prop

- src/components/Box/Box.tsx
This merge makes the `fw` prop support not only Prismane's default values but any other valid string or number value.
> feat: add dual value support to fw prop

- src/components/Field/FieldWrapper/FieldWrapper.tsx
This merge makes all field components to occupy the full width of the parent.
> feat: fields to occupy full parent width

- src/components/TextField/TextField.tsx
This merge fixes an issue with the `TextField` component's `prefix` prop.
> fix: fix TextField prefix position

- src/hooks/useOutsideClick/useOutsideClick.test.tsx
- src/hooks/useOutsideClick/useOutsideClick.ts
This merge adds a third parameter to the `useOutsideClick` hook, which enables us to define an array of events that the callback should be called on.
> feat: add events param to useOutsideClick

- src/components/Portal/Portal.stories.tsx
- src/components/Portal/Portal.tsx
This merge improves the performance of the `Portal` component, removing the unnecessary usage of `useState` and `useEffect` hooks.
> perf: improve Portal component

- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/TabsTab/TabsTab.tsx
This merge adds a `disabled` prop to the `Tabs.Tab` component, allowing us to disable given tabs.
> feat: add disabled prop to TabsTab component

- src/components/Table/Table.tsx
- src/components/Table/TableCell/TableCell.tsx
This merge makes the `Table` component occupy the entire width of its parent.
> feat: make Table to occupy the entire parent width

- src/components/Table/TableBody/TableBody.tsx
- src/components/Table/TableCell/TableCell.tsx
- src/components/Table/TableRow/TableRow.tsx
This merge fixes an issue where a border was shown in the `Table.Head` component.
> fix: fix TableHead border

- src/components/Menu/MenuLabel/MenuLabel.tsx
This merge makes the `Menu.Label` component provide a margin on top to visually separate menu sections.
> feat: make MenuLabel provide spacing between sections

- src/hooks/useDraggable/useDraggable.ts
- src/hooks/useFocusTrap/useFocusTrap.ts
This merge adds generic type ref support to the `useDraggable` and `useFocusTrap` hooks.
> feat: add generic type ref support to hooks
