prismaneui/prismane

- src/validators/email/email.test.ts
- src/validators/email/email.ts
This merge will fix the email validator and will mark emails like "johndoe@domain....com" as invalid and emails like "johndoe@domain.college" will be marked as valid.
> Fix email validator to disallow given emails

- src/components/Accordion/AccordionItem/AccordionItemContext.ts
- src/components/ActionButton/ActionButton.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/CloseButton/CloseButton.tsx
- src/components/SelectField/SelectField.tsx
This merge fixes the prop type errors in Breadcrumb component's internal components.
> Fix Breadcrumb Internal Components Prop Types

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/hooks/useId/useId.stories.tsx
This merge fixes the Button component's full prop and the button does not grow vertically now.
> Fix Button Component's Full Prop

- src/types.ts
- tsconfig.json
This merge will fix the Style Props type to allow styles that use pseudo-classes.
> Fix Pseudo Class Style Prop Types

- src/hooks/useCopyToClipboard/index.ts
- src/hooks/useCopyToClipboard/useCopyToClipboard.stories.tsx
- src/hooks/useCopyToClipboard/useCopyToClipboard.test.tsx
- src/hooks/useCopyToClipboard/useCopyToClipboard.ts
Hey, firstly, I wanted to say thanks, guys, for such a good UI library. I was playing with _Prismane_ for a few days and found it interesting. Also, I wanted to contribute (if it's possible), so here's my first contribution. I added the useCopyToClipboard hook. I hope it can be helpful in some way. ;)
> Added new hook /  useCopyToClipboard ✨

- src/components/Form/Form.stories.tsx
- src/validators/after/after.test.ts
- src/validators/after/after.ts
- src/validators/before/before.test.ts
- src/validators/before/before.ts
This merge fixes the error message on before and after date validators, now the date is in correct format.
> Fix before and after validators error message

- src/hooks/index.ts
- src/hooks/useNetworkStatus/index.ts
- src/hooks/useNetworkStatus/useNetworkStatus.stories.tsx
- src/hooks/useNetworkStatus/useNetworkStatus.test.tsx
- src/hooks/useNetworkStatus/useNetworkStatus.ts
This merge introduces the useNetworkStatus hook that tracks if the user is online and offline
> Add useNetworkStatus Hook

- src/hooks/index.ts
- src/hooks/useFocusTrap/index.ts
- src/hooks/useFocusTrap/useFocusTrap.stories.tsx
- src/hooks/useFocusTrap/useFocusTrap.test.tsx
- src/hooks/useFocusTrap/useFocusTrap.ts
This merge will introduce the new useFocusTrap hook, which focuses the first focusable element of a container or a specific one.
> Add use trap focus hook

- src/hooks/index.ts
- src/hooks/useSearch/index.ts
- src/hooks/useSearch/useSearch.stories.tsx
- src/hooks/useSearch/useSearch.test.tsx
- src/hooks/useSearch/useSearch.ts
This merge introduces the useSearch hook which simplifies handling data and searching through it.
> Add useSearch Hook

- src/components/Footer/Footer.stories.tsx
- src/components/Footer/Footer.test.tsx
- src/components/Footer/Footer.tsx
- src/components/Footer/index.ts
- src/components/index.ts
This merge introduces the new Footer component.
> Add Footer Component

- src/components/Header/Header.stories.tsx
- src/components/Header/Header.test.tsx
- src/components/Header/Header.tsx
- src/components/Header/index.ts
- src/components/index.ts
This merge introduces the Header component.
> Introduce Header Component

- src/components/Main/Main.stories.tsx
- src/components/Main/Main.test.tsx
- src/components/Main/Main.tsx
- src/components/Main/index.ts
- src/components/index.ts
This merge introduces the Main component.
> Introduce Main Component

- src/components/PrismaneProvider/index.ts
- src/components/PrismaneProvider/usePrismaneColor/index.ts
- src/components/PrismaneProvider/usePrismaneColor/usePrismaneColor.stories.tsx
- src/components/PrismaneProvider/usePrismaneColor/usePrismaneColor.test.tsx
- src/components/PrismaneProvider/usePrismaneColor/usePrismaneColor.ts
- src/components/PrismaneProvider/useThemeModeValue/index.ts
- src/components/PrismaneProvider/useThemeModeValue/useThemeModeValue.stories.tsx
- src/components/PrismaneProvider/useThemeModeValue/useThemeModeValue.test.tsx
- src/components/PrismaneProvider/useThemeModeValue/useThemeModeValue.ts
- src/components/index.ts
This merge introduces the useThemeModeValue hook. This hook allows to easily toggle style values based on the theme mode.
> Add useThemeModeValue Hook

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Radio/Radio.tsx
- src/components/Switch/Switch.tsx
- src/components/TextField/TextField.stories.tsx
This merge fixes inconsistencies in label sizes of checkable fields.
> Fix label sizes

- src/components/Field/Field.tsx
- src/index.css
- src/types.ts
This merge fixes an issue with the field color after autocomplete that occurs on Chrome-based web browsers.
> Fix Autocomplete Color

- src/components/Button/Button.tsx
This merge fixes an issue where the Button component's background color when using secondary variant was inconsistent in light and dark mode.
> Fix Button Secondary Variant Background Color

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Field/Field.tsx
- src/components/Field/useFieldProps.ts
- src/components/Radio/Radio.tsx
- src/types.ts
This merge fixes an issue where if the indeterminate state was ignored if the checkbox didn't have a value.
> Fix checkbox indeterminate state

- src/components/Grid/Grid.stories.tsx
- src/components/Grid/GridItem/GridItem.tsx
- src/components/Radio/Radio.test.tsx
This merge fixes the columnSpan and rowSpan props of the Grid.Item component.
> Fix Grid.Item Span Props

- src/components/Field/useFieldProps.ts
- src/components/Radio/Radio.stories.tsx
- src/components/Radio/RadioGroup/RadioGroup.tsx
This merge introduces the `label` and `error` props to the `Radio.Group` component.
> Add Label And Error Prop To Radio.Group Component

- src/hooks/useForm/useForm.stories.tsx
- src/hooks/useForm/useForm.ts
This merge introduces error handling in the `useForm` hook.
> Add Error Handling In useForm Hook

- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
This merge introduces improved positions of the `Badge` component.
> Improve Badge Positions

- src/components/TextareaField/TextareaField.tsx
This merge fixes the class names of the TextareaField component.
> Fix TextareaField ClassNames

- src/components/Box/Box.stories.tsx
- src/hooks/useStyling/useStyling.ts
This adds a recursion to the `sx` prop, passing the `theme` object to every property, not only top-level ones.
> Recursively pass theme to sx prop values

- src/components/Button/Button.tsx
- src/components/Chip/Chip.tsx
- src/components/Text/Text.tsx
- src/components/Tooltip/Tooltip.tsx
This merge adds default colors to the `Text` component.
> Add Default Colors To Text Component

- src/components/Button/Button.tsx
- src/components/Grid/Grid.stories.tsx
- src/components/Radio/RadioGroup/RadioGroup.tsx
- src/components/Skeleton/Skeleton.tsx
This merge removes a console.log() left inside the Radio component.
> Remove console.log() from Radio.Group component

- src/components/Button/Button.tsx
This merge fixes the background of the Button component's secondary variant when using dark theme mode.
> Fix Secondary Button Background Dark Theme

- src/components/Gradient/Gradient.tsx
This merge fixes the `Gradient` component's prop types.
> fix: fix gradient prop types

- src/components/Container/Container.tsx
This merge fixes the prop type for the `maxSize` prop of the `Container` component.
> fix: fix container prop type

- src/components/Field/Field.stories.tsx
This merge refactors the `Field.Label` component's story to honor the right prop.
> refactor: fix for prop in field label story

- src/types.ts
This merge fixes the sx prop's prop type.
> fix: fix sx prop type

- src/components/PinField/PinField.tsx
This merge fixes an issue with the hidden field of the `PinField` component.
> fix: fix PinField's hidden field

- src/components/Paper/Paper.tsx
This merge fixes the overflow of the `Paper` component.
> fix: fix paper component overflow

- src/components/Transition/Transition.tsx
This merge fixes the transition properties of the `Transition` component.
> fix: fix transition properties

- src/components/Dialog/Dialog.tsx
This merge adds default animations to the `Dialog` component based on the value of the `position` prop.
> feat: add default animations to Dialog based on position

- src/components/Spinner/Spinner.stories.tsx
- src/components/Spinner/Spinner.tsx
This merge adds a `color` prop to the `Spinner` component.
> feat: add color prop to Spinner component

- src/components/Progress/Progress.stories.tsx
- src/components/Progress/Progress.tsx
This merge adds a `color` prop to the `Progress` component.
> feat: add color prop to Progress component

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/TableCaption/TableCaption.tsx
- src/components/Table/TableCell/TableCell.tsx
- src/components/Table/TableContext.ts
This merge adds a `size` prop to the `Table` component, allowing us to control the `font-size` and `padding` of the cells, and ultimately - the size of the table.
> feat: add size prop to Table component

- src/components/Box/Box.tsx
This merge fixes the prop types of the `Box` component.
> fix: fix Box component prop types
